<a href="https://colab.research.google.com/github/Deeps-G/DL-by-pytorch/blob/main/NN%20By%20Manual_vs_builtIn_func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import torch.nn as nn
import torch.optim as optim

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=["id", "Unnamed: 32"], inplace=True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
X_train, X_test, y_train, y_test =train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
scaler= StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [9]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [10]:
print("x train data",X_train)
print("y train data",y_train)

x train data [[-0.92592531 -0.85005516 -0.89642465 ... -0.57696472 -0.54537531
   1.24960372]
 [ 0.17102028  1.0983868   0.20944914 ...  0.67264496  0.65736166
   0.23185986]
 [-0.55183874 -0.28800459 -0.57273428 ... -0.4450326   0.48995368
  -0.5445133 ]
 ...
 [-0.36901447 -0.29268835 -0.37278378 ... -0.58307976 -0.22356191
  -0.3031426 ]
 [-0.75435177 -1.09126853 -0.74973964 ... -0.65875346  0.03973997
   0.37679003]
 [-0.25088187 -1.29501186 -0.26625277 ... -0.3924432  -0.29345068
  -0.62532939]]
y train data [0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 1 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 1
 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 1 0 0 1
 1 1 0 0 1 0 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 1 1 1 1 1 0 1 0
 0 1 0 1 0 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0 0 1 1
 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1
 0 0 0 1 0 1 1 0 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 1 1
 0 0 0 1 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1
 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 0 0 1 1
 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 1 0 0 0 0 1 0 1 0
 0 1 0 1 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 0 0 1 0
 0 0 1 1 0 1 1 0 0 0 0]

As they are numpy arrays, we have to convert them into tensors

In [23]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [24]:
X_train_tensor.shape, X_test_tensor.shape, y_train_tensor.shape, y_test_tensor.shape

(torch.Size([455, 30]),
 torch.Size([114, 30]),
 torch.Size([455]),
 torch.Size([114]))

Defining the model

In [39]:
class improvedNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)
    return out
# class manualNN():
#   def __init__(self,X):
#     self.weights=torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
#     self.bias=torch.zeros(1, dtype=torch.float64, requires_grad=True)
#   def forward(self, X):
#     z=torch.matmul(X, self.weights) + self.bias
#     y_pred=torch.sigmoid(z)
#     return y_pred
  # def loss_function(self, y_pred, y):
  #   # Clamp predictions to avoid log(0)
  #   epsilon = 1e-7
  #   y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

  #   # Calculate loss
  #   loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
  #   return loss

In [60]:
learning_rate=0.1
epochs=25

In [61]:
loss_func=nn.BCELoss()

In [62]:
model=improvedNN(X_train_tensor.shape[1])
optimizer=torch.optim.SGD(model.parameters(),lr=learning_rate)
for epoch in range(epochs):
  y_pred=model(X_train_tensor)
  loss=loss_func(y_pred, y_train_tensor.view(-1,1))
  optimizer.zero_grad()
  loss.backward()
  with torch.no_grad():
    optimizer.step()
    # model.linear.weight-=learning_rate*model.linear.weight.grad
    # model.linear.bias-=learning_rate*model.linear.bias.grad
    # model.linear.weight.grad.zero_()
    # model.linear.bias.grad.zero_()

# model=manualNN(X_train_tensor)
# for epoch in range(epochs):
#   y_pred=model.forward(X_train_tensor)
#   loss=model.loss_function(y_pred, y_train_tensor)
#   loss.backward()
#   with torch.no_grad():
#     model.weights-=learning_rate*model.weights.grad
#     model.bias-=learning_rate*model.bias.grad
#     model.weights.grad.zero_()
#     model.bias.grad.zero_()
  print(f"Epoch: {epoch+1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.6177776455879211
Epoch: 2, Loss: 0.4936574399471283
Epoch: 3, Loss: 0.42226067185401917
Epoch: 4, Loss: 0.37564003467559814
Epoch: 5, Loss: 0.34223073720932007
Epoch: 6, Loss: 0.316776305437088
Epoch: 7, Loss: 0.2965528964996338
Epoch: 8, Loss: 0.27999046444892883
Epoch: 9, Loss: 0.26611068844795227
Epoch: 10, Loss: 0.25426673889160156
Epoch: 11, Loss: 0.24401135742664337
Epoch: 12, Loss: 0.23502402007579803
Epoch: 13, Loss: 0.22706788778305054
Epoch: 14, Loss: 0.2199636548757553
Epoch: 15, Loss: 0.21357287466526031
Epoch: 16, Loss: 0.2077864557504654
Epoch: 17, Loss: 0.2025173008441925
Epoch: 18, Loss: 0.1976948231458664
Epoch: 19, Loss: 0.1932610720396042
Epoch: 20, Loss: 0.18916814029216766
Epoch: 21, Loss: 0.18537580966949463
Epoch: 22, Loss: 0.18185025453567505
Epoch: 23, Loss: 0.17856261134147644
Epoch: 24, Loss: 0.1754881739616394
Epoch: 25, Loss: 0.1726056933403015

In [63]:
model.linear.bias

Parameter containing:
tensor([-0.0742], requires_grad=True)

In [64]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5964912176132202